service:
  name: generate-receipt
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  profile: serverless-admin

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
  generate_receipt:
    handler: src/handler.generate_receipt
    events:
      - http:
          method: post
          path: receipt
          cors: true
